node('jdk24_mvn3') {
    checkout scm
    def common = load 'jenkins.d/Jenkinsfile-common.groovy'

    stage('Check Push User') {
        script {
            def pusher = sh(returnStdout: true, script: "git log -1 --pretty=format:'%an'").trim()
            if (!["jens-breitenstein"].contains(pusher)) {
                currentBuild.result = 'NOT_BUILT'
                error("Build skipped: pushed by unauthorized user '$pusher'")
            }
        }
    }

    stage('Build & Deploy Java 24') {
        common.setupMavenSettings()
        dir('java24') {
            echo "=== Building java24 with Maven 3.9.6 ==="
            sh '''
                mvn -q -ntp clean install \
                    -Djenkins.jobName=$JOB_NAME \
                    -Djenkins.buildNumber=$BUILD_NUMBER \
                    -Djenkins.nodeName=$NODE_NAME
            '''

            sh 'mvn -q -ntp deploy -DskipTests'
        }
    }
}
