node('jdk8_mvn3') {
    checkout scm
    def common = load 'jenkins.d/Jenkinsfile-common.groovy'

    stage('Build with Maven 3.2.5') {
        common.setupMavenSettings()
        dir('java8') {
            echo "=== Building java8 with Maven 3.2.5 ==="
            sh '''
                $MAVEN_HOME/bin/mvn clean install
            '''
        }
    }

    stage('Deploy with Maven 3.2.5') {
        common.setupMavenSettings()
        dir('java8') {
            echo "=== Deploying java8 with Maven 3.x ==="
            sh '''
                $MAVEN3_HOME/bin/mvn -v
                $MAVEN3_HOME/bin/mvn deploy -DskipTests
            '''
        }
    }
}
