node('jdk8_mvn2') {
    checkout scm
    def common = load 'jenkins.d/Jenkinsfile-common.groovy'

    stage('Build with Maven 3.x') {
        common.setupMavenSettings()
        dir('java8') {
            echo "=== Building java8 with Maven 3.x ==="
            sh '''
                # $MAVEN2_HOME/bin/mvn -v
                $MAVEN3_HOME/bin/mvn clean install
            '''
        }
    }

    stage('Deploy with Maven 3.9.x (modern upload)') {
        common.setupMavenSettings()
        dir('java8') {
            echo "=== Deploying java8 with Maven 3.x ==="
            sh '''
                $MAVEN3_HOME/bin/mvn -v
                $MAVEN3_HOME/bin/mvn deploy -DskipTests
            '''
        }
    }
}
