pipeline {
    agent { label 'jdk8_mvn2' }

    triggers {
        githubPush()
    }

    stages {
        stage('Build with JDK 8 / Maven 2.2.1') {
            steps {
                echo "=== Building jdk8-app with Java 8 + Maven 2.2.1 ==="
                sh '''
                    echo "Environment:"
                    java -version
                    mvn -v
                    echo "Hello from JDK 8 build!"
                    mvn clean package -DskipTests
                '''
            }
        }
    }

    post {
        success {
            echo "Build on Java 8 successful."
        }
        failure {
            echo "Build on Java 8 failed."
        }
        always {
            cleanWs()
        }
    }
}
